# .github/workflows/tracker.yml

name: Equity Tracker

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  run-tracker:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tracker
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: python tracker.py

      - name: Commit CSV Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add *.csv

          git commit -m "update tracking data" || echo "no changes"

          git push
